### ISSUE TITLE
Add --exclude ansible-lint option to permit exluding certain folders ?

### ISSUE THREAD

**Issue by levequej** [mschuchard/linter-ansible-linting#10]
Hello,

It would be nice to be able to select certain folders to exclude from linting ( In my case I want to exclude community roles folder from linting). That corresponds to the ansible-lint --exclude option.

Thanks,
Julien

**Comment by mschuchard** [comment]
Although this is a setting that is really only feasible on a per-project basis, it appears that providing a nonexistent directory as a value to the `--exclude` argument has no effect, so this should be a safe config option to add.

I will put this in the roadmap.

**Comment by levequej** [comment]
thx :)

**Comment by mschuchard** [comment]
Added in 0961e14ef69bc33d6fdd6183820ddfabad0018e0.
