### ISSUE TITLE
Issue when saving

### ISSUE THREAD

**Issue by jacobamey** [mschuchard/linter-ansible-linting#11]
hello, when I save a file I get an error in the upper right of atom. It appears to be complaining about system based packages. I am currently working with in Fedora 25.

- unexpected end of file for BASH_FUNC_sc1 and BASH_FUNC_module

I've included a picture of the error in question.

![weird-error](https://cloud.githubusercontent.com/assets/3608280/22277867/f874f8ce-e28c-11e6-9771-4221583772af.png)

everything seems to work fine until linter-ansible-linting is enabled.

**Comment by mschuchard** [comment]
You have hit on the famous Fedora BASH bug. Check AtomLinter/linter-puppet-lint#68 (coincidentally a repo I maintain) for the original report and fix.

**Comment by jacobamey** [comment]
Haha, I love the "Famous Fedora BASH bug" comment. It really does look famous by all the links to the original submitter. 

Well thank you, that was a pretty easy fix at least. for everyone else, I can confirm in Fedora 25 this fix is still viable.

The Fix:
`sudo dnf remove scl-utils`

reboot and your good to go.

**Comment by finkelamein** [comment]
How is this a proper fix? messing about with packages that will most likely be installed for a reason?
What if people DO need this package?

As mentioned in the puppet lint issue, people are using docker to debug their code.
