### ISSUE TITLE
ENOENT Error

### ISSUE THREAD

**Issue by fia5000** [mschuchard/linter-ansible-linting#13]
Seeing 
`spawn ansible-lint ENOENT`

**Comment by mschuchard** [comment]
That means you have a permissions issue usually. Check to see if the user running Atom has necessary permissions for the directories and files being checked, or has permissions to run ansible-lint itself.

**Comment by mschuchard** [comment]
ping @fia5000

**Comment by fia5000** [comment]
@mschuchard I checked the permissions and they were messed up. I am guessing something got screwed up between Atom beta upgrades. I reset permissions and all works. 

Thanks for your help!
