### ISSUE TITLE
Non Array error thrown on open

### ISSUE THREAD

**Issue by fferguson** [mschuchard/linter-ansible-linting#15]
The following error is shown every time I open atom or a new file. 

This package is actually throwing the error:

[https://github.com/steelbrain/linter](url)

![screenshot from 2017-03-14 14-15-26](https://cloud.githubusercontent.com/assets/26222166/23904837/306abd22-08c1-11e7-9148-9512b75d65c2.png)

**Comment by mschuchard** [comment]
This is the Ansible-Lint linter. You should post this in the Ansible linter (linter-ansible-syntax).
