### ISSUE TITLE
Doesnt work on windows

### ISSUE THREAD

**Issue by Mugen1991** [mschuchard/linter-ansible-linting#18]
Can't get it to run. I am missing the module "grp" 
Can I install it somehow?

**Comment by mschuchard** [comment]
I just double-checked and Ansible cannot be used from a Windows control machine. If you installed it within a Windows 10 bash or cygwin just to have an installation presence, then you can set up Atom to work with that. If you are having difficulties running Atom from either of those, then I suggest heading to a Stack Exchange site or Atom or some other place for technical support.

**Comment by Mugen1991** [comment]
I will try to do it the cygwin-way. Thanks for this tip :-)
