### ISSUE TITLE
Error when opening an file encrypted by ansible-vault

### ISSUE THREAD

**Issue by mariusvw** [mschuchard/linter-ansible-linting#21]
To encrypt and decrypt yml files I use the ansible-vault (https://atom.io/packages/ansible-vault)  package.

The problem seems to occur just before ansible-vault has the chance to decrypt the file and reload the editor view.

Attached an screenshot showing the situation.

![screen shot 2017-07-13 at 17 39 03](https://user-images.githubusercontent.com/201711/28174842-e825ee10-67f2-11e7-87af-a9b1e708b014.jpg)

**Comment by mschuchard** [comment]
I have `ansible-vault` support in `linter-ansible-syntax` because `ansible`, of course, has intrinsic knowledge and support of `ansible-vault`. I don't think `ansible-lint` has any kind of integration with `ansible-vault`, so it expects the file to be decrypted prior to execution.

Let me see what kind of workarounds are available here. I assume this is occurring upon opening the file and not when triggered during a save?

**Comment by mariusvw** [comment]
@mschuchard indeed, it only happens when opening the file, so if the order could be changed on some way that your plugin would be able to wait for the decrypt it could be solved. Not sure if that is possible.

**Comment by mschuchard** [comment]
Ok, thanks for confirming the assumption. I have a couple options here to fix this.

**Comment by mschuchard** [comment]
So I forgot to mention that I could do a workaround here, but the better option is to add the functionality to ansible-lint directly willthames/ansible-lint#115. I am not sure if I know how to do the implementation though based on the 'discovery' I have done to this point.

**Comment by mschuchard** [comment]
It has been several months and none of us have added `ansible-vault` support to `ansible-lint`. I am going to add a catch to the package to simply display an `info` level notification on this error explaining that the file in question needs to be decrypted first. I think this is going to be the best path forward on this.

Comments on this are welcome.

**Comment by mschuchard** [comment]
Mitigated in 076bf99438eeb6e34962948db648438cd29f1df3.
