### ISSUE TITLE
Error when opening .yml, .yaml files: spawn ansible-lint ENOENT

### ISSUE THREAD

**Issue by itblaked** [mschuchard/linter-ansible-linting#23]
Hi,

I'm new to using a linter and Ansible so apologies if i've missed something obvious but I can't seem to get this to run at all in Atom. I'm getting the below error anytime I open a .yml file in Atom, regardless of contents of file (happens with blank .yml). If I disable linter-ansible-linting i don't get the error on opening .yml files.

"An unexpected error with ansible, ansible-lint, linter-ansible-linting, atom, linter, and/or your playbook, has occurred.
spawn ansible-lint ENOENT"

Screen grab attached as well.

![linter-ansible-linting](https://user-images.githubusercontent.com/26047814/30091434-f17fb8bc-92fc-11e7-8bd6-68d1257234de.png)

Running Fedora 26 workstation, Atom v1.19.0, linter-ansible-linting v1.3.0, language-ansible v0.2.1, linter v2.2.0

**Comment by mschuchard** [comment]
ENOENT means the executable is either not installed or you installed in such a way that the user running Atom does not have permissions to use it. How did you install ansible-lint?

**Comment by itblaked** [comment]
Within the atom app in packages...

**Comment by mschuchard** [comment]
So was that with `pip`, or your package manager, or from source etc?

**Comment by Arcanemagus** [comment]
@itblaked This package (`linter-ansible-linting`) is a wrapper around [`ansible-lint`](https://pypi.python.org/pypi/ansible-lint) which you need to have installed using `pip`, some other package manager, or directly from [the source](https://github.com/willthames/ansible-lint) before you can use this package.

**Comment by itblaked** [comment]
Apologies @mschuchard @Arcanemagus, you were both right, i hadn't installed ansible-linter via pip as it says clearly in the package details that i rushed through, thanks for your help and patience
