### ISSUE TITLE
Allow disabling ansible-lint on some files, e.g docker-compose.yml

### ISSUE THREAD

**Issue by ludovicc** [mschuchard/linter-ansible-linting#25]
Ansible-lint tries to verify every yaml file, but not all yaml files are for Ansible...

How can we disable it one some file patterns, for example docker*.yml ?

**Comment by mschuchard** [comment]
So at the moment the package executes ansible-lint on everything that Atom recognizes as Ansible. By the language-ansible package, this is by default everything that ends in `.yml`, but can also be manually specified.

I would have to add a new feature for this; some kind of blacklist feature. Besides your example, this would also be helpful for `.travis.yml` and others, so I kind of want this myself.

**Comment by mschuchard** [comment]
Double-checked and realized I had forgotten linter-ansible-syntax has code to ignore anything that is not a playbook already, so that is ok.

Added this feature in 3524827aba07b99640a7ec8c4ca50ecd9b5dd3f6. Works correctly for me with the test cases I tried. Will be in the next release (soon?).
