### ISSUE TITLE
it seems to provide warnings about missing named tasks but doesn't detect real errors

### ISSUE THREAD

**Issue by larsf** [mschuchard/linter-ansible-linting#28]
Adding this to my playbook does not result in an error:

kljlkjlkj;lkj;lkjj
  - block:

**Comment by mschuchard** [comment]
This linter leverages `ansible-lint` for style warnings. If you want to lint for syntax errors, then you want to use `linter-ansible-syntax` to leverage `ansible`'s syntax linting.
