### ISSUE TITLE
Install on macOS

### ISSUE THREAD

**Issue by Asgoret** [mschuchard/linter-ansible-linting#30]
Hi! Can you help with install on macOS?))) What i need install except ansible?

**Comment by mschuchard** [comment]
Please consult the [documentation](https://github.com/mschuchard/linter-ansible-linting#installation).

**Comment by Asgoret** [comment]
> Please consult the [documentation](https://github.com/mschuchard/linter-ansible-linting#installation).

Ths! I forgot install ansible-lint through pip
