### ISSUE TITLE
unable to parse /etc/ansible/hosts as an inventory source

### ISSUE THREAD

**Issue by MarkJamesHub** [mschuchard/linter-ansible-linting#31]
Folder Structure...

1. //Product1
    1. /group_vars
    1. /inventory/hosts
    1. /roles
    1. create1.yml
1. //Product2
    1. /group_vars
    1. /inventory/hosts
    1. /roles
    1. create2.yml

When linting the create_.yml files it does not seem to recognise my folder structure and defaults to my local host file system i.e. /etc/ansible/hosts as an inventory source

Is there a way to make linter understand my Folder Structure (I have literally dozens of Product folders)

**Comment by mark1709** [comment]
Folder Structure...

//Product1
    /group_vars
    /inventory/hosts
    /roles
    create1.yml
//Product2
    /group_vars
    /inventory/hosts
    /roles
    create2.yml

When linting the create_.yml files it does not seem to recognise my folder structure and defaults to my local host file system i.e. /etc/ansible/hosts as an inventory source

Is there a way to make linter understand my Folder Structure (I have literally dozens of Product folders)

**Comment by mschuchard** [comment]
I believe this is something that is set in an ansible config local to the playbook. If you execute `ansible-lint` on the `create?.yml`, do you have the same issue?

**Comment by mschuchard** [comment]
No updates in a year; closing.
