### ISSUE TITLE
Make timeout for linter a setting.

### ISSUE THREAD

**Issue by flamein** [mschuchard/linter-ansible-linting#32]
It would be awesome if timeout as defined in `.atom/packages/linter-ansible-linting/node_modules/atom-linter/lib/helpers.js` would be configurable. 

We have several playbooks that take more then the hardcoded 10 seconds to execute.
And they're not even huge playbooks. Even a playbook with just 3 roles added to hosts will trigger this.

**Comment by mschuchard** [comment]
This is honestly the first I am hearing that the atom-linter dep has that setting across any of my packages.

I will take a look into this and ping the owner for assistance if necessary.

**Comment by mschuchard** [comment]
Turns out it was available in the sb-exec api: https://github.com/steelbrain/exec/blob/master/README.md#api.

Added in commit 5afa3da.

Will be in the next release, or you can patch in the `lib/main.js` immediately.
