### ISSUE TITLE
When running Ansible-lint on playbook "This file, an include, or role has a syntax error"

### ISSUE THREAD

**Issue by ericsysmin** [mschuchard/linter-ansible-linting#33]
However if I run this same thing from command line, I have no problems getting the specific errors

[502] All tasks should be named
[703] Should change default metadata: license

etc....

**Comment by mschuchard** [comment]
Can you provide a [`MCVE`](https://stackoverflow.com/help/reprex)?

**Comment by dnorthup-ums** [comment]
@mschuchard I've actually been seeing the same for some time. Unfortunately it is sporadic enough that producing the gold-standard "minimum complete verifiable example" is excessively difficult. Usually I just futz with something seemingly completely unrelated and the error then magically goes away.

(I had to Google that FLA as my brain's decoder ring only does TLAs and that stackoverflow page is gone.)

**Comment by mschuchard** [comment]
YAML and Ansible syntax errors now displaying. Let me know if this is an edge case not covered by recent changes.
