### ISSUE TITLE
When click on an warning, Linter creates a new file instead of opening it.

### ISSUE THREAD

**Issue by firemdkfighter** [mschuchard/linter-ansible-linting#36]
And Atom show error:
![image](https://user-images.githubusercontent.com/7867180/85257494-278c0700-b490-11ea-8ab8-c71e67a3c6ed.png)

**Comment by mschuchard** [comment]
These are actually two separate issues. The first is that you either do not have `ansible-lint` installed, or have not provided the path to it in the config. The second is that you are trying to save the file to a directory that either does not exist or you do not have access to, but that is unrelated to any Atom packages or `ansible-lint`.
