### ISSUE TITLE
Warning: "Please upgrade your version of ansible-lint to >= 3.5." when ansible-lint 5.0.0 is installed

### ISSUE THREAD

**Issue by redsoftwaresolutions** [mschuchard/linter-ansible-linting#41]
![image](https://user-images.githubusercontent.com/76572690/108235330-917dae80-70fa-11eb-9211-7df672f9725e.png)

**Comment by mschuchard** [comment]
Coincidentally fixed in the release earlier this morning. Refer to [documentation](https://github.com/mschuchard/linter-ansible-linting#installation) for remedy.
