### ISSUE TITLE
Build failed - Package doesn't work correctly

### ISSUE THREAD

**Issue by Alucard616** [mschuchard/linter-ansible-linting#42]
Hi there!
I just wanted to try out this package with my atom-editor, but unfortunately, it doesn't work at all. Nothing is shown, if there are any errors.
I installed the dependencies "linter" and "language-ansible", but i do not get any errors.

So I looked here, if theres anything know and saw, that the build is failing.
After that, I checked, if e.g. "linter-yaml" is working. It does.

I really hope, this could be fixed :)

Regards
Patrick

**Comment by mschuchard** [comment]
I would need more information about your environment to assist with debugging why your setup is not working.

**Comment by Alucard616** [comment]
I'm working on a Fedora 34 Workstation and my Atom Version is 1.57.0
What information do you also need? I'm a lil' bit lost, sorry.

**Comment by mschuchard** [comment]
Versions of ansible-lint and ansible would be the most relevant here.

**Comment by Alucard616** [comment]
oh, sure, sorry.

here you go:
pip show ansible-lint
Name: ansible-lint
Version: 5.0.12

**Comment by mschuchard** [comment]
and ansible's version?

Also the package has been acceptance tested as valid against ansible-lint 3.5-5.0.12 and ansible 2.0-2.11 on Linux, so you are probably going to need to do some heavier debugging on your end to find the edge case here that may not be covered yet.

**Comment by Alucard616** [comment]
In our deployment, we use ansible 2.10.10

i have installed ansible 2.9.23 but don't use it.
When i call "ansible" in my console, a script + a docker container is triggered.

I see no error in Atom.
It's just, that nothing happens.

**Comment by mschuchard** [comment]
Ok at this point I need a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example). If I can reproduce the issue, then i will be able to begin hunting down the cause. If I cannot, then you will need to troubleshoot your environment setup (probably with others at technical assistance resource sites). If you can determine what in your environment is causing this issue and you cannot rectify it yourself, then I will need to expand the code to cover your setup.

**Comment by Alucard616** [comment]
OK
I hope, this helps you, to reproduce it.
First:
I deleted all my aliases regarding to ansible, to make sure, this is not the problem.
It's still the same after that.

Sooo
I'm working on a Fedora Workstation 34
Ansible is installed via dnf source in version 2.9.23
After that I installed ansible-lint (with yamllint) via pip3 with: pip3 install "ansible-lint[yamllint]"
Version is ansible-lint 5.0.12 using ansible 2.9.23

I opened the atom editor, go to the settings and search for the linter-ansible-linter package and install it.
Then I install the dependencies: linter and language-ansible.
After these two additional packages are also installed, i restart atom, so linter can get some more packages

After that, linter is ready

I'll open some yml-file in my ansible project and there is nothing shown in linter.
I'll recheck with ansible-linter from my console, where i see some issues.

I see no error message, that linter-ansible isn't working or something. Just nothing happens.
When I install the yamllint package after that, i see the yamllint errors within the linter.

my yml example is:
`---
  - name: some shell command
    shell: echo bong`

ansible-lint should give me the errors, that the indentation isn't correct + shell should not be used with a single command

**Comment by mschuchard** [comment]
As an isolated task list, that file yields the following display with Linter-Ansible-Linting, Ansible-Lint 5.0.12, and Ansible 2.11.2 on Linux:

> Error	Ansible-Lint	syntax-check: 'shell' is not a valid attribute for a Play	2:5	null/foo.yml

which evinces the interesting point that ansible-lint expects to only lint roles or playbooks, so an isolated task list has a `null` type for the project when an isolated task list, which gives me an interetsting TODO out of this. It also is the expected output because that is a syntax issue on 2.11.2. I am unsure what the output should be with Ansible 2.9.23, but probably something about not using the `shell` module when `command` would suffice.

Interestingly enough, if I fix the module to be `ansible.builtin.shell` then Ansible-Lint still throws the same error, which points at a bug in Ansible-Lint. Both of these issues are just coincidental though, and the takeaway is you will indeed need to debug your environment setup to proceed further.

**Comment by Alucard616** [comment]
Aahh, good to know.

I put an extra yml in some of my role tasks and tested it there.
Sorry, for not telling.

When I user ansible-lint there, I get this message:
```ansible-lint -p test.yml 
WARNING  Listing 3 violation(s) that are fatal
test.yml:2: command-instead-of-shell Use shell only when shell functionality is required
test.yml:2: no-changed-when Commands should not change things if nothing needs doing
test.yml:2: yaml wrong indentation: expected 0 but found 2 (indentation)```


Interestingly, after I started Atom today, I got, for the first time, an error from ansible-lint:

> [Linter] Error running Ansible-Lint Error: Failed to spawn command `~/.local/bin/ansible-lint`. Make sure `~/.local/bin/ansible-lint` is installed and on your PATH

When I check on my console, it is found:
```whereis ansible-lint 
ansible-lint: /home/alucard616/.local/bin/ansible-lint```

**Comment by mschuchard** [comment]
That error is thrown from `sb-exec`, which linter packages rely on for spawning shell processes. It would be the usual debugging around pathing, permissions, etc. Note also that just because your user in your shell environment has access to that path does not mean Atom does also, since those two processes can be spawned with different environments.

**Comment by Alucard616** [comment]
Hi there!

I checked my atom PATH:

```
process.env.PATH
"/home/myuser/.local/bin:/home/myuser/bin:/home/myuser/.local/bin:/home/myuser/bin:/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin"
```

This seems correct to me, so I don't really know, where this error comes from.

Anyways. I changed the executable path in the ansible-linter to an absolute path.

Sadly, I'm back at: nothing happens.


Again I created a new file in my ansible-project:

ansible
-> roles
---> some_role
-----> tasks
-------> test.yml

same example:
```
---
  - name: some shell command
    shell: echo bong
```

```
ansible-lint -p test.yml 
WARNING  Listing 3 violation(s) that are fatal
test.yml:2: command-instead-of-shell Use shell only when shell functionality is required
test.yml:2: no-changed-when Commands should not change things if nothing needs doing
test.yml:2: yaml wrong indentation: expected 0 but found 2 (indentation)
```

and in atom, there is nothing, sadly

**Comment by mschuchard** [comment]
If you need assistance with your personal environment compatibility with Atom and Atom packages, then you should either open a new issue or check with available support channels/groups/etc.
