### ISSUE TITLE
Move to Pulsar

### ISSUE THREAD

**Issue by EHEX-schildt** [mschuchard/linter-ansible-linting#49]
After Atom sunsetting: https://github.blog/2022-06-08-sunsetting-atom

is there a change we get this plugin to ppm (Pulsar Package Manager)
https://github.com/pulsar-edit/package-backend/blob/main/docs/reference/packages.md

At the moment we get v1.8.0 from ppm.

**Comment by mschuchard** [comment]
Once there is a stable release of Pulsar with standardized package management, there can be a migration. Until then this is acceptance tested and intended for use with Atom 1.63.0-dev (the last release from Atom community). Pulsar has about one month of further development compared to that version of Atom.
