### ISSUE TITLE
role/tasks/main.yml is not a playbook.

### ISSUE THREAD

**Issue by bbaassssiiee** [mschuchard/linter-ansible-linting#8]
Linter says: "Error 'file' is not a valid attribute for a Play".
But project/roles/role/tasks/main.yml is not a playbook.

- name: 'make sure .bashrc exists'
  become: no
  file: path=~/.bashrc state=file

**Comment by mschuchard** [comment]
I am pretty sure you meant to file this under the 'linter-ansible-syntax' project and this is worked around in the upcoming update.

**Comment by mschuchard** [comment]
Sixteen days with no reply. Going to assume this is for 'linter-ansible-syntax' and that it pertains to what was fixed in the relevant commit. Closing.
