### ISSUE TITLE
Doesn't Work with OS X

### ISSUE THREAD

**Issue by aes512** [mschuchard/linter-ansible-linting#9]
I am getting errors on OSX identical to https://github.com/mschuchard/linter-ansible-linting/issues/6.

Is there a known fix for OSX Atom clients that leverage this plugin?

**Comment by mschuchard** [comment]
That issue was due to a unique package in Redhat distros that had a bug in it. I am sure your issue is stemming from something different.

Do you have any info about your environment that might be causing your Atom packages, especially linters or this linter, to not function?

**Comment by mschuchard** [comment]
Soft ping.

**Comment by mschuchard** [comment]
Hard ping @aes512.

**Comment by aes512** [comment]
@mschuchard nothing. This is OSX 10.11.6 with Atom 1.11.2. I installed linter-ansible-lintting (1.2.0 at present) from the atom package manager.

**Comment by mschuchard** [comment]
Try again with 1.2.1 since it throws the full error to your Atom notifications.

**Comment by aes512** [comment]
@mschuchard that seems to have fixed my issues, thanks!
